### ISSUE TITLE
HAL_PCD_EP_Flush() fails with linking error for non OTG devices

### ISSUE THREAD

**Issue by daniel-starke** [STMicroelectronics/STM32CubeF1#22]
**Describe the set-up**
Use the function HAL_PCD_EP_Flush() with a STM32F103 board.

**Describe the bug**
The linker fails with

    undefined reference to `USB_FlushTxFifo'

and

    undefined reference to `USB_FlushRxFifo'

in function `HAL_PCD_EP_Flush`.
The function is defined here:
https://github.com/STMicroelectronics/STM32CubeF1/blob/6ead386a08dea17f4dffbdbcd36c9979cb53588b/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_pcd.c#L1857-L1873

But `USB_FlushTxFifo` and `USB_FlushRxFifo` are only declared and not defined for non-OTG devices.
See
https://github.com/STMicroelectronics/STM32CubeF1/blob/6ead386a08dea17f4dffbdbcd36c9979cb53588b/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c#L380
and
https://github.com/STMicroelectronics/STM32CubeF1/blob/6ead386a08dea17f4dffbdbcd36c9979cb53588b/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c#L402

The declarations for the non-OTG variant can be found here without any matching function definition.
https://github.com/STMicroelectronics/STM32CubeF1/blob/6ead386a08dea17f4dffbdbcd36c9979cb53588b/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_usb.h#L605-L606

**Comment by ALABSTM** [comment]
Hi @daniel-starke,

Thank you for this report. You are absolutely right. `USB_FlushTxFifo()` and `USB_FlushRxFifo()` functions were not defined for STM32F1 devicing not supporting OTG feature.

Actually this issue has already been detected and fixed. The fix is already available in the frame of the **v1.8.2** release published a couple of weeks ago. The linking error should disappear once you will upgrade to this version. 

Below is how the `USB_FlushTxFifo()` has been defined for the non-OTG variants:
https://github.com/STMicroelectronics/STM32CubeF1/blob/003dfc9e6c2e424c19a25df3934afaf7fce660d6/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c#L1905-L1917

Thank you again for your contribution.

With regards,
