### ISSUE TITLE
CubeMX TIM Remap with LL Generation

### ISSUE THREAD

**Issue by viteo** [STMicroelectronics/STM32CubeF1#57]
**Describe the set-up**
STM32F103C8, STM32F103RB
CubeIDE 1.12.0, CubeMX 6.8.0-RC4

**Describe the bug**
Configuring TIM3 as input capture on non-default channel pin (i.e TIM3_CH1 ~ PA6 default, remap available to PB4, PC6).
When Driver Selector for TIM is set to HAL library it generates `__HAL_AFIO_REMAP_TIM3_PARTIAL();` or `__HAL_AFIO_REMAP_TIM3_ENABLE();` respectivelly.
When Driver Selector is set to LL it doesn't generate the remap command, although it does generate GPIO initialization. (missing `LL_GPIO_AF_RemapPartial_TIM3()` or `LL_GPIO_AF_EnableRemap_TIM3()`)

**How To Reproduce**
1. New CubeMx / CubeIDE project
2. Set PB4 pin as TIM3_CH1
3. Configure TIM3: Trigger Source: TI1FP1, Channel 1: Input Capture direct mode, Channel 2: Input Capture indirect mode
4. Project Manager tab -> Advanced Settings -> Driver Selector -> TIM -> Change from HAL to LL.
5. Generate code.

To start the timer enable IT, enable Channels, enable Counter, but nothing happens because GPIO is not remapped at the configuration stage.
On the other hand HAL remaps GPIO beforehand and enabling timer with `HAL_TIM_IC_Start_IT(..)` does the job.

**Additional context**
LL generates Remap when configuring TIM channel as PWM Output.

**Screenshots**
![image](https://user-images.githubusercontent.com/9247937/227982022-e2831aa0-4700-4290-8b30-a09e19d1aad5.png)

**Comment by TOUNSTM** [comment]
Hi @viteo,

The point you reported is actually related to the CubeMX generation problem and not to the firmware published in this repository. Unfortunately, we don't treat aspect related to CubeMX tool in our GitHub repositories. They are rather treated at the [STM32CubeMX](https://community.st.com/s/topic/0TO0X000000BTr8WAG/stm32cubemx) dedicated page of the ST Community .

Since this issue is not directly related to the STM32Cube firmware but rather to our ecosystem, please allow me then to close this thread. Thank you for your comprehension.

With regards,

**Comment by viteo** [comment]
Did you forward this issue to your ecosystem? Or I should open this again?
